### ISSUE TITLE
Game freezing and crashing due to subtitles

### ISSUE THREAD

**Issue by N3ksiak** [Corporal1Lambda/SCP-SL-Custom-Translation-Files#2]
game freezes when using the translation pack, figured out its due to subtitles its probably due to unicode/emojis.
here is a footage of this happening
https://www.youtube.com/watch?v=RQETYB6BaPQ

How to replicate?
Download the translations pack launch game on mtf spawn players and game will freeze but you will still be able to move around and after 30 seconds to a minute the game will close without any other errors

Temp fix
Disable subtitles or remove the subtitles.txt file it will auto generate on game launch and give you stock subtitles

**Comment by Corporal1Lambda** [comment]
fixed

**Comment by Corporal1Lambda** [comment]
Fixed already
